flask_rag_service/models.py
from datetime import datetime, UTC
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import DeclarativeBase

db = SQLAlchemy()


def utc_now() -> datetime:
    """Helper to return UTC datetime for created and updated metadata columns

    Returns:
        datetime: Current timestamp in Coordinated Universal Time (UTC)
    """
    return datetime.now(UTC)


class Base(DeclarativeBase):
    id: Mapped[int] = db.Column(
        db.Integer,
        primary_key=True,
        autoincrement=True,
    )
    created: Mapped[datetime] = db.Column(db.DateTime, default=utc_now)
    updated: Mapped[datetime] = db.Column(
        db.DateTime,
        default=utc_now,
        onupdate=utc_now,
    )


class User(db.Model):
    username: Mapped[str] = db.Column(db.String, unique=True, nullable=False)
    password: Mapped[str] = db.Column(db.String, nullable=False)


class Collection(db.Model):
    name: Mapped[str] = db.Column(db.String, nullable=False)
    user_id: Mapped[int] = db.Column(
        db.Integer,
        db.ForeignKey(User.id),
        nullable=False,
    )
    user = db.relationship("User")


class Document(db.Model):
    name: Mapped[str] = db.Column(db.String, nullable=False)


class Chunk(db.Model):
    content: Mapped[str] = db.Column(db.String, nullable=False)

flask_rag_service/__init__.py
from celery import Celery
from celery import Task
from flask import Flask
from flask import session
from flask import redirect
from flask import url_for
from flask import render_template
from flask_jwt_extended import JWTManager
from flask_jwt_extended import jwt_required
from flask_jwt_extended import get_jwt_identity
from flask_bcrypt import Bcrypt
from flasgger import Swagger
from .models import db


def create_app() -> Flask:
    # Define and configure Flask app
    app = Flask(__name__)
    app.config.from_pyfile("config.py", silent=True)

    # Initialize Celery, SQLAlchemy, JWT, Swagger extensions
    celery_init_app(app)
    db.init_app(app)
    jwt = JWTManager(app)
    app.extensions["jwt"] = jwt
    bcrypt = Bcrypt(app)
    app.extensions["bcrypt"] = bcrypt
    # Custom configuration to limit Swagger to auth / api routes
    swagger = Swagger(app, config=app.config['SWAGGER_CONFIG'])
    app.extensions["swagger"] = swagger

    # Define base index route
    @app.get("/")
    @jwt_required(optional=True)
    def index() -> str:
        """Index page, redirect to login if no token available

        Returns:
            str: Index or login page
        """
        # Check if user is logged in
        current_user = get_jwt_identity()
        if current_user:
            return render_template("index.html")
        else:
            return redirect(url_for("login"))

    @app.get("/login")
    def login() -> str:
        """Login page to sign up or provide credentials

        Returns:
            str: Login page with signup/in form
        """
        return render_template("login.html")

    # Register blueprints for auth and API
    from . import auth
    from . import views

    app.register_blueprint(auth.auth_bp)
    app.register_blueprint(views.api_bp)

    return app


def celery_init_app(app: Flask) -> Celery:
    class FlaskTask(Task):
        def __call__(self, *args: object, **kwargs: object) -> object:
            with app.app_context():
                return self.run(*args, **kwargs)

    celery_app = Celery(app.name, task_cls=FlaskTask)
    celery_app.config_from_object(app.config["CELERY"])
    celery_app.set_default()
    app.extensions["celery"] = celery_app
    return celery_app

flask_rag_service/auth.py
from datetime import datetime
from flask import Blueprint
from flask import request
from flask import jsonify
from flask import current_app
from flask_jwt_extended import create_access_token
from flask_jwt_extended import create_refresh_token
from flask_jwt_extended import get_jwt_identity
from flask_jwt_extended import jwt_required
from flask_jwt_extended import set_access_cookies
from flask_jwt_extended import unset_jwt_cookies

from .models import db, User

auth_bp = Blueprint("auth", __name__, url_prefix="/auth")


@auth_bp.post("/users/create")
def create_user():
    """Endpoint to create a new user
    ---
    definitions:
      User:
        type: object
        properties:
          username:
            type: string
          password:
            type: string
    content:
      'application/x-www-form-urlencoded':
        schema:
          $ref: User
    responses:
      201:
        description: User successfully created
        examples:
          id: 1
          username: myuser
    """
    # App extension for password encryption
    bcrypt = current_app.extensions["bcrypt"]
    hashed_pw = bcrypt.generate_password_hash(request.form["password"])
    user = User(
        username=request.form["username"],
        password=hashed_pw,
    )
    db.session.add(user)
    db.session.commit()

    return jsonify(
        id=user.id,
        username=user.username,
    ), 201


@auth_bp.post("/login")
def auth_login():
    """Endpoint to exchange user credentials for an access token
    ---
    definitions:
      User:
        type: object
        properties:
          username:
            type: string
          password:
            type: string
    content:
      'application/x-www-form-urlencoded':
        schema:
          $ref: User
    responses:
      200:
        description: Token successfully generated
        examples:
          access_token: "eyJ0eXAiOiJKV1QiLCJhbGci..."
          refresh_token: "KV1QiLCJhbGcieyJ0eXAiOiJ..."
          expires: "2024-07-14T12:00:00Z"
      401:
        description: Invalid username or password
      404:
        description: User not found
    """
    # App extension for password encryption
    bcrypt = current_app.extensions["bcrypt"]
    # Get user from database by username
    username = request.form["username"]
    user = db.one_or_404(
        db.select(User).filter_by(username=username),
        description=f"No user named '{username}'.",
    )
    # Check password against database
    password = request.form["password"]
    if bcrypt.check_password_hash(user.password, password):
        response = jsonify(message="Login successful")
        # Generate access token and refresh token
        jwt_expires = current_app.config["JWT_ACCESS_TOKEN_EXPIRES"]
        access_token = create_access_token(identity=username, fresh=True)
        refresh_token = create_refresh_token(identity=username)
        expiration = datetime.now() + jwt_expires
        set_access_cookies(response, access_token)
        return jsonify(
            access_token=access_token, refresh_token=refresh_token, expires=expiration,
        )
    else:
        return jsonify(message="Invalid username or password"), 401


@auth_bp.post("/refresh")
@jwt_required(refresh=True)
def auth_refresh():
    # Generate access token using refresh token
    identity = get_jwt_identity()
    jwt_expires = current_app.config["JWT_ACCESS_TOKEN_EXPIRES"]
    access_token = create_access_token(identity=identity, fresh=False)
    expiration = datetime.now() + jwt_expires
    return jsonify(access_token=access_token, expires=expiration)


@auth_bp.post("/logout")
def logout():
    response = jsonify(message="logout successful")
    unset_jwt_cookies(response)
    return response

flask_rag_service/views.py
from flask import Blueprint
from flask import request
from flask import jsonify
from flask import current_app
from flask_jwt_extended import get_jwt_identity
from flask_jwt_extended import jwt_required

from .models import db, User, Collection
from . import tasks

api_bp = Blueprint("api", __name__, url_prefix="/api")


@api_bp.get("/users/<id>/collections")
@jwt_required
def user_collections(id: str) -> dict[str, object]:
    """Method to list collections for a user.
    ---
    parameters:
      - name: palette
        in: path
        type: int
        required: true
    responses:
      200:
        description: A list of collections
        examples:
          collections: [{'id': 1, 'name':'test'}]
    """
    # Get collections for authenticated user
    current_user = get_jwt_identity()
    collections = (
        db.session.query(Collection)
        .join(
            Collection.user,
        )
        .filter_by(User.username == current_user)
        .scalars()
    )
    # Return collections
    return jsonify(
        collections=collections,
    )

flask_rag_service/templates/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Flask RAG Service</title>
  </head>
  <body>
    <h2>Retrieval Augmented Generation</h2>
    Load documents, which are pre-processed in the background then made available for
    augmented Generative AI chat.

    <hr />
    <h4>Document Collections</h4>
    Upload documents to enable RAG chat.
  </body>
</html>

flask_rag_service/templates/login.html
<!doctype html>
<html>
<head>
  <meta charset=UTF-8>
  <title>Flask RAG Service</title>
</head>
<body>
<h2>Retrieval Augmented Generation</h2>
Load documents, which are pre-processed in the background then made available for augmented Generative AI chat.

<hr>
<button id="login-button">Login</button>
<button id="signup-button">Sign Up</button>
<div id="login-div" style="display: none;">
  <h4>Login</h4>
  <form id=login method=post action="{{ url_for("auth.login") }}">
    <label>Username: <input type=text name=username required></label><br>
    <label>Password: <input type=password name=password required></label><br>
    <input type=submit>
  </form>
  <p id="login-message" style="color: red; display: none;">Invalid username or password</p>
</div>
<div id="signup-div" style="display: none;">
  <h4>Sign Up</h4>
  <form id=signup method=post action="{{ url_for("auth.users.create") }}">
    <label>Username: <input type=text name=username minlength=5 required></label><br>
    <label>Password: <input type=password name=password minlength=10 required></label><br>
    <input type=submit>
  </form>
</div>

<script>
  // Button elements
  const signUp = document.getElementById("#signup");
  const logIn = document.getElementById("#login");
  // Signup button handler
  document.getElementById("#signup-button").addEventListener("click", () => {
    signUp.style.display = "block";
  });
  // Signup button handler
  document.getElementById("#login-button").addEventListener("click", () => {
    logIn.style.display = "block";
  });
  // Signup form handler
  document.forms['signup'].addEventListener("submit", (event) => {
    event.preventDefault()
    fetch(event.target.action, {
      method: "POST",
      body: new FormData(event.target)
    })
    .then(response => {
      // Show login form after signup
      signUp.style.display = "none";
      logIn.style.display = "block";
    })
  });
  // Login form handler
  document.forms['login'].addEventListener("submit", (event) => {
    event.preventDefault()
    fetch(event.target.action, {
      method: "POST",
      body: new FormData(event.target)
    })
    .then(response => {
      const data = response.json();
      if (response.ok) {
        // Redirect to index page
        window.location.href = "/";
      } else {
        // Update and show error message
        const loginMessage = document.getElementById("#login-message");
        loginMessage.innerText = data.message;
        loginMessage.style.display = "block";
      }
    })
  });
</script>
</body>
</html>